<?php
    $memoryBefore=memory_get_usage();
    echo("p04\n");
    $id=readline();
    $city_map=["A"=>10,"B"=>11,"C"=>12,"D"=>13,"E"=>14,"F"=>15,"G"=>16,"H"=>17,"I"=>34,"J"=>18,"K"=>19,"L"=>20,"M"=>21,"N"=>22,"O"=>35,"P"=>23,"Q"=>24,"R"=>25,"S"=>26,"T"=>27,"U"=>28,"V"=>29,"W"=>32,"X"=>30,"Y"=>31,"Z"=>33];
    $sum=0;
    $city_code=substr($id,0,1);
    $sum=$sum+((int)($city_map[$city_code]/10)+((int)(substr($city_map[$city_code],1,1))*9));
    for($i=2;$i<=9;$i=$i+1){
        $sum=$sum+((int)(substr($id,(10-$i),1))*($i-1));
    }
    $sum=$sum+(int)(substr($id,9,1));
    if($sum%10==0){
        echo("Y".PHP_EOL);
    }else{
        echo("N".PHP_EOL);
    }
    $memoryAfter=memory_get_usage();
    $memoryDifference=$memoryAfter-$memoryBefore;
    echo("memory used ".($memoryDifference/1048576)."MB");
?>