<?php
    $memoryBefore=memory_get_usage();
    echo("p08\n");
    $n=trim(fgets(STDIN));
    $ans=[];
    for($i=0;$i<$n;$i=$i+1){
        $ans[]=trim(fgets(STDIN));
    }
    for($i=0;$i<count($ans);$i=$i+1){
        if((1<$num)&&($num<(2**63-1))){
            $all=0;
            for($i=1;$i<$num;$i=$i+1){
                if($num%$i==0){
                    $all=$all+$i;
                }
            }
            if($all==$i){
                echo("Y".PHP_EOL);
            }else{
                echo("N".PHP_EOL);
            }
        }else{
            echo("N".PHP_EOL);
        }
    }
    $memoryAfter=memory_get_usage();
    $memoryDifference=$memoryAfter-$memoryBefore;
    echo("memory used: ".($memoryDifference/1048576)."MB");
?>