<?php
    $memoryBefore=memory_get_usage();
    echo("p13\n");
    $n=(int)(fgets(STDIN));
    $ans=[];
    for($i=0;$i<$n;$i=$i+1){
        $hashvalue=0;
        $str=trim(fgets(STDIN));
        if(strlen($str)<=65536){
            for($j=0;$j<strlen($str);$j=$j+1){
                $true=false;
                $hash=(ord($str[$j]))*(31**(strlen($str)-($j+1)));
                if($hashvalue>(2**31)-1){
                    $hash=$hash+($hash-2**32);
                    $true=true;
                }
                if($hashvalue<-2**31){
                    $hash=$hash+($hash+2**32);
                    $true=true;
                }
                if($true==false){
                    $hashvalue=$hashvalue+$hash;
                }
            }
            $ans[]=$hashvalue;
        }else{
            echo("輸入未符合要求");
        }
    }
    for($i=0;$i<count($ans);$i=$i+1){
        echo("output".($i+1)."=>".$ans[$i]."\n");
    }
    echo("\n");
    $memoryAfter=memory_get_usage();
    $memoryDifference=$memoryAfter-$memoryBefore;
    echo("memory used: ".($memoryDifference/1048576)."MB");
?>