<?php
    include("../link.php");
    $success=false;
    $usernumber="未知";
    $data="未知錯誤請重新登入";
    if($_POST["submit"]){
        $username=$_POST["username"];
        $password=$_POST["password"];
        $verifycodeans=$_POST["verifycodeans"];
        $verifycodeuserans=$_POST["verifycodeuserans"];
        if($row=query($db,"SELECT*FROM `user` WHERE `username`=?",[$username])){
            $row=$row[0];
            if($row[2]==$password){
                if($verifycodeans==$verifycodeuserans){
                    $success=true;
                    $usernumber=$row[4];
                    $data=[
                        "id"=>$row[0],
                        "permission"=>$row[5]
                    ];
                }else{
                    $usernumber=$row[4];
                    $data="驗證碼有誤";
                }
            }else{
                $usernumber=$row[4];
                $data="密碼有誤";
            }
        }else{
            $usernumber="未知";
            $data="帳號有誤";
        }
    }

    echo(json_encode([
        "success"=>$success,
        "usernumber"=>$usernumber,
        "data"=>$data
    ]));
?>